[project]
name = "compy6502"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "doit",
    "ipython>=9.13.0",
    "py65==1.1.0",
    "pyserial>=3.5",
    "pytest",
    "ruff",
]

[tool.pytest.ini_options]
testpaths = ["test/asm"]
pythonpath = ["test"]

[tool.ruff]
line-length = 120
target-version = "py311"
